In [1]:
import numpy as np

In [4]:
X = np.random.normal(size=(11,11,4))
X

array([[[  1.28108837e+00,  -8.08892400e-01,   5.46200645e-01,
           7.64702861e-01],
        [  1.05455681e+00,  -3.25165987e-01,   6.84351074e-01,
          -2.16914568e+00],
        [ -3.93006343e-01,  -2.77073093e-01,  -2.00337758e+00,
           4.02695551e-01],
        [ -2.35222133e-01,  -1.49996312e-01,   7.23664978e-01,
          -4.33993932e-01],
        [ -7.05013097e-01,  -1.43458917e+00,   1.20279277e+00,
           5.80188296e-01],
        [ -1.38900411e+00,   9.20000840e-01,   7.89077694e-02,
          -5.30039606e-02],
        [ -2.23279063e-01,  -1.67151960e-01,  -1.62086289e+00,
           1.03266174e+00],
        [ -4.12434339e-01,  -4.74791643e-01,  -1.14645074e-01,
          -4.60122237e-01],
        [  3.51631317e-01,  -1.14283485e+00,  -8.23864798e-01,
           3.40090140e-01],
        [  2.34290521e-01,  -6.37860147e-01,   1.67362496e+00,
          -1.87150832e-02],
        [ -1.30605886e+00,  -1.16966319e+00,   5.42566068e-01,
           5.71772901e-01]]

In [9]:
W0 = np.random.normal(size=(5,5,4))
W0

array([[[ 0.61463913, -0.78238985,  0.86197863,  0.46995537],
        [ 1.83784821, -0.12907472, -0.0028517 , -0.06432476],
        [ 0.3565259 , -0.49352395, -0.83992256, -1.04168508],
        [-2.43567904, -1.35686431,  0.70800476,  1.06187553],
        [-0.89162962, -0.59789034, -0.12472684,  0.01185536]],

       [[ 0.53383873,  1.23162894,  0.02307995, -0.54046598],
        [-0.87493068, -1.38523606, -0.29194604,  1.11763389],
        [ 0.66759344,  0.20580915,  0.08205381,  0.60076485],
        [ 0.99920552,  0.47262725,  0.11092184, -1.4915543 ],
        [-0.61328078,  0.26340977, -0.4171025 ,  0.06731139]],

       [[ 2.1656235 , -0.97218254, -1.39860351, -0.42434116],
        [-1.45180909, -1.2749501 ,  0.25897395,  2.23906445],
        [ 0.08192593,  0.84445936,  0.50852147, -0.66534405],
        [ 0.48674195, -0.9660522 ,  1.15895358,  1.31882622],
        [-1.97333117, -1.4418663 , -0.6497019 , -0.24433181]],

       [[-1.1305216 ,  1.35900482, -0.53728411, -1.39469165],
  

In [13]:
Z = X[:5,:5,:] * W0
Z

array([[[  7.87407041e-01,   6.32869206e-01,   4.70813283e-01,
           3.59376215e-01],
        [  1.93811534e+00,   4.19707093e-02,  -1.95156677e-03,
           1.39529765e-01],
        [ -1.40116941e-01,   1.36742206e-01,   1.68268203e+00,
          -4.19481946e-01],
        [  5.72925621e-01,   2.03524643e-01,   5.12358246e-01,
          -4.60847535e-01],
        [  6.28610558e-01,   8.57727006e-01,  -1.50020536e-01,
           6.87834322e-03]],

       [[ -5.85215558e-01,   8.51649336e-01,  -3.07297718e-04,
          -1.17162772e-01],
        [  1.41361351e+00,  -1.63923877e+00,  -4.23844390e-01,
          -8.55300563e-01],
        [  2.41707737e-01,  -5.00733778e-02,  -1.03762602e-01,
          -2.93068912e-01],
        [  8.29523516e-01,   5.32764713e-01,  -9.81812140e-02,
           1.78763339e+00],
        [  3.20991118e-01,   2.28374891e-01,  -2.72562554e-01,
           1.35672832e-01]],

       [[ -1.22691998e+00,  -8.47096288e-01,  -2.83882761e+00,
          -6.49689211e-

In [25]:
X[:5,:5,:]

array([[[ 1.28108837, -0.8088924 ,  0.54620065,  0.76470286],
        [ 1.05455681, -0.32516599,  0.68435107, -2.16914568],
        [-0.39300634, -0.27707309, -2.00337758,  0.40269555],
        [-0.23522213, -0.14999631,  0.72366498, -0.43399393],
        [-0.7050131 , -1.43458917,  1.20279277,  0.5801883 ]],

       [[-1.09624036,  0.69148208, -0.01331449,  0.21678103],
        [-1.6156863 ,  1.18336421,  1.45179015, -0.76527794],
        [ 0.36205828, -0.24330005, -1.26456768, -0.48782633],
        [ 0.83018308,  1.12724078, -0.88513869, -1.19850373],
        [-0.52339993,  0.86699476,  0.6534666 ,  2.01560002]],

       [[-0.56654353,  0.8713346 ,  2.02975867,  1.53105397],
        [ 0.69780601, -0.50624857,  0.98388152,  0.89081648],
        [ 0.00737774,  1.82770192,  0.80678843, -0.60741413],
        [ 0.23414307,  0.06613074,  0.03832304,  0.09293353],
        [-1.8090548 , -1.21735059,  0.36820779, -0.34400506]],

       [[ 0.17196882,  1.28286865,  0.1029482 ,  0.77420032],
  

In [5]:
X2 = np.random.normal(size=(2,2,4))
X2

array([[[ 0.02594861, -0.63412025,  1.0634821 ,  1.08580574],
        [-0.31985462,  0.0349726 , -0.44269568,  0.76713566]],

       [[ 0.36570319, -0.98075735, -1.0661876 ,  0.04503166],
        [-1.65629243, -0.36520822,  0.28160471, -0.95544295]]])

In [7]:
X2[:,0,:]

array([[ 0.02594861, -0.63412025,  1.0634821 ,  1.08580574],
       [ 0.36570319, -0.98075735, -1.0661876 ,  0.04503166]])

In [19]:
U = [[2,2],[1,1]]
U = np.array(U)
U

array([[2, 2],
       [1, 1]])

In [22]:
D = [[5,5],[3,3]]
D = np.array(D)
D

array([[5, 5],
       [3, 3]])

In [23]:
D *U

array([[10, 10],
       [ 3,  3]])

In [24]:
D.dot(U)

array([[15, 15],
       [ 9,  9]])